### PR TITLE
[MM-36747] Allow users to specify spellchecker url for downloading dictionaries

### LINKED ISSUE #1642: Why does it connect to Google on start?
- [x] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [ ] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Environment**
- Operating System: Linux, Debian Testing, amd64
- Mattermost Desktop App version: v4.7.0 b757742 (unofficial .DEB)
- Mattermost Server version: does not matter

**Steps to reproduce**
Start Mattermost

**Expected behavior**
Not connect to any server until a server is defined

**Observed behavior**
Connections to https://redirector.gvt1.com

> strings $(which mattermost-desktop)|grep gvt1.com
https://redirector.gvt1.com/edgedl/chrome/dict/
{"origin":"https://gvt1.com/","has_same_origin_collector":false,"collectors":["https://beacons.gcp.gvt2.com/domainreliability/upload","https://beacons.gvt2.com/domainreliability/upload","https://beacons2.gvt2.com/domainreliability/upload","https://beacons3.gvt2.com/domainreliability/upload","https://beacons4.gvt2.com/domainreliability/upload","https://beacons5.gvt2.com/domainreliability/upload","https://beacons5.gvt3.com/domainreliability/upload","https://clients2.google.com/domainreliability/upload"],"path_prefixes":["/videoplayback","/videochunk","/chunk_present","/cm2_state","/videolookup","/videogoodput","/MotifFiles","/StudioFiles","/packdata","/edgedl","/market","/packages","/crx","/initplayback","/initsegment",""],"success_sample_rate":0.05,"failure_sample_rate":1.0,"include_subdomains":true}

### PR DESCRIPTION
**Pull request by Willyfrog**
#### Summary

This PR allows people who would prefer not to download dictionary definitions from chromium's CDN to use an alternate url.

This requires a separate PR for documenting the process.
This requires a separate PR for cherry-picking into master as we moved towards TS

Testing this is complicated, I've detailed the steps in the jira ticket, but feel free to DM me if you need any help

#### Ticket Link

Fixes #1642 
[MM-36747](https://mattermost.atlassian.net/browse/MM-36747)

#### Device Information
This PR was tested on: windows and linux

#### Release Note

```release-note
Allow users to specify a different download location for hunspell dictionaries
```

### CODE REVIEW

File: src/main/main.js [hunk 1]
```diff
@@ -458,6 +459,25 @@ function handleNewServerModal() {
 
 function initializeAfterAppReady() {
     app.setAppUserModelId('Mattermost.Desktop'); // Use explicit AppUserModelID
+    const defaultSession = session.defaultSession;
+
+    defaultSession.on('spellcheck-dictionary-download-failure', (event, lang) => {
+        if (config.spellCheckerURL) {
+            log.error(`There was an error while trying to load the dictionary definitions dor ${lang} fromfully the specified url. Please review you have access to the needed files. Url used was ${config.spellCheckerURL}`);
```
Comment (nevyangelova) [inline src/main/main.js:466]: typo:)

File: src/renderer/components/SettingsPage.jsx [hunk 2]
```diff
@@ -464,6 +493,53 @@ export default class SettingsPage extends React.PureComponent {
...
 
+        if (process.platform !== 'darwin') {
+            if (this.state.spellCheckerURL === null || typeof this.state.spellCheckerURL === 'undefined') {
+                options.push(
+                    <Button
+                        id='editSpellcheckerURL'
+                        key='editSpellcheckerURL'
+                        onClick={() => this.setState({spellCheckerURL: '', allowSaveSpellCheckerURL: false})}
+                        bsStyle='link'
+                    >{'Use alternate dictionary URL'}</Button>,
```
Comment (nevyangelova) [inline src/renderer/components/SettingsPage.jsx:504]: I am not sure do we mean alternate or alternative? Sorry

**Review by nevyangelova — COMMENTED** [review]
otherwise LG :)

File: src/renderer/components/SettingsPage.jsx (hunk 2 above)
Comment (Willyfrog) [reply src/renderer/components/SettingsPage.jsx]: alternative, thanks! I've just changed it

**Review by nevyangelova — APPROVED** [review]

**Review by devinbinnie — APPROVED** [review]

**Comment by amyblais** [comment]
@Willyfrog I think this wasn't cherry-picked to master yet.

**Comment by Willyfrog** [comment]
no, I'm working on this one, seems something change and it is not behaving properly, but will get cherrypicked today

**Comment by Willyfrog** [comment]
@amyblais added cherry picking and documentation PRs
