### PR TITLE
[MM-38857] Fix spellcheck locales regex

### LINKED ISSUE #1754: [5.0.0-rc1] 'Select preferred Language(s)' causes forgotten Server at app restart and whitescreen until resized
- [x] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**

with [5.0.0-rc1](https://github.com/mattermost/desktop/releases/tag/v5.0.0-rc1) the set servers (or all config) is forgotten when restarting the app

**Environment**
- Operating System: KUbuntu 20.04
- Mattermost Desktop App version: 5.0.0-rc1
- Mattermost Server version: 5.37.1

**Steps to reproduce**
- Have `mattermost-desktop` set up and successfully connected to your server (either with 5.0.0-rc1 or wit previous stable 4.7.2)
- restart `mattermost-desktop`
- be greeted with whitescreen and no server connected
- resize window to get the "connect to server" dialog

**Expected behavior**
remember server over app restarts

**Observed behavior**
forgetting server and having whitescreen

Whitescreen on restart

whitescreen on restart

window after resizing showing "Add Server" dialog
window after resizing

nothing interesting in commandline output
```sh
$ mattermost-desktop 
08:34:23.392 › Current working directory is /home/nero, changing into /opt/Mattermost
08:34:23.702 › config.autostart has been configured: true
08:34:23.703 › config.autostart has been configured: true
08:34:23.786 › preloading with /opt/Mattermost/resources/app.asar/modalPreload.js
08:34:23.812 › config.autostart has been configured: true
```

I also tried to remove the `.config/Mattermost` folder, connected to the server, and restartet the app. Also forgot the server again

**Possible fixes**

### PR DESCRIPTION
**Pull request by devinbinnie**
#### Summary
This PR fixes the regex used for validating spell checker locales. It was previously expecting locales with a dash, which not all of them have.

#### Ticket Link
Closes #1754.
https://mattermost.atlassian.net/browse/MM-38857

```release-note
NONE
```

### CODE REVIEW

File: src/main/Validator.ts [hunk 1]
```diff
@@ -119,7 +119,7 @@ const configDataSchemaV3 = Joi.object<ConfigV3>({
     useSpellChecker: Joi.boolean().default(true),
     enableHardwareAcceleration: Joi.boolean().default(true),
     autostart: Joi.boolean().default(true),
-    spellCheckerLocales: Joi.array().items(Joi.string().regex(/^[a-z]{2}-[A-Z]{2}$/)).default([]),
+    spellCheckerLocales: Joi.array().items(Joi.string().regex(/^[A-Za-z-]+$/)).default([]),
```
Comment (Willyfrog) [inline src/main/Validator.ts:122]: we should limit the size, I don't think there is more than 5 or 6 chars, but anyway it is a standard so we can probably check on that.
Either that or accept any string and lookup the values later in the app

**Review by Willyfrog — CHANGES_REQUESTED** [review]

File: src/main/Validator.ts (hunk 1 above)
Comment (Willyfrog) [reply src/main/Validator.ts:122]: actually, I don't really see much value on this regex validation: a string is just fine

**Review by Willyfrog — APPROVED** [review]
