### PR TITLE
[MM-60232] Fix a crash in Linux when trying to create a thumbnail from an image

### LINKED ISSUE #3129: [Crash]: TypeError: s.nativeImage.createThumbnailFromPath is not a function
### Before you file a crash report

- [X] I have checked the [issue tracker](https://github.com/mattermost/desktop/issues) and have not found an issue that matches the one I'm filing.
- [X] This issue doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/mattermost-server/issues).
- [X] I have read the [contribution guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

### Mattermost Desktop Version

Version 5.9.0

### Operating System

Debian 12.6

### Mattermost Server Version

9.4.1

### What type of crash did you experience?

Uncaught exception (I saw a dialog pop up that said "The Mattermost app quit unexpectedly")

### Crash report details

```shell
Application: Mattermost 5.9.0
Platform: Linux 6.9.7+bpo-amd64 x64
TypeError: s.nativeImage.createThumbnailFromPath is not a function
    at C.formatDownloadItem (/tmp/user/1000/.mount_matter8OQjCH/resources/app.asar/index.js:2:258218)
    at C.upsertFileToDownloads (/tmp/user/1000/.mount_matter8OQjCH/resources/app.asar/index.js:2:255626)
    at C.doneEventController (/tmp/user/1000/.mount_matter8OQjCH/resources/app.asar/index.js:2:256982)
    at DownloadItem.<anonymous> (/tmp/user/1000/.mount_matter8OQjCH/resources/app.asar/index.js:2:254788)
    at Object.onceWrapper (node:events:634:26)
    at DownloadItem.emit (node:events:519:28)
```

### Log Output

```shell
[2024-08-19 15:47:01.873] [error] Logger Log level set to: info
[2024-08-19 15:47:02.021] [warn]  [App.Initialize] Current working directory is /home/sabrina, changing into /tmp/user/1000/.mount_matterCxVGUC
[2024-08-19 15:47:02.252] [info]  [App.Config] config.autostart has been configured: false
[2024-08-19 15:47:02.615] [info]  [ServerDropdownView] init
[2024-08-19 15:47:02.759] [warn]  [i18nManager] Failed to set new language en-US
[2024-08-19 15:47:02.759] [warn]  [i18nManager] Failed to set new language US
[2024-08-19 15:47:03.013] [info]  [App.Config] config.autostart has been configured: false
[2024-08-19 15:47:03.709] [info]  [App.Config] config.autostart has been configured: false
[2024-08-19 15:47:07.479] [info]  [UpdateManager] Checking for update
[2024-08-19 15:47:07.669] [info]  [UpdateManager] Update for version 5.9.0 is not available (latest version: 5.9.0, downgrade is disallowed).
[2024-08-19 15:48:01.261] [error] Logger Log level set to: info
[2024-08-19 15:48:01.426] [warn]  [App.Initialize] Current working directory is /home/sabrina, changing into /tmp/user/1000/.mount_matterkNoXsz
[2024-08-19 15:48:01.655] [info]  [App.Config] config.autostart has been configured: false
[2024-08-19 15:48:01.888] [error] [MainWindow] Error: Provided bounds info are outside the bounds of your screen, using defaults instead.
    at P.getSavedWindowState (/tmp/user/1000/.mount_matterkNoXsz/resources/app.asar/index.js:2:819478)
    at P.init (/tmp/user/1000/.mount_matterkNoXsz/resources/app.asar/index.js:2:815824)
    at P.show (/tmp/user/1000/.mount_matterkNoXsz/resources/app.asar/index.js:2:818038)
    at /tmp/user/1000/.mount_matterkNoXsz/resources/app.asar/index.js:2:213809
    at zr (/tmp/user/1000/.mount_matterkNoXsz/resources/app.asar/index.js:2:214532)
```

### Additional Information

Crash occurred when hovering over an image, and clicking on the Download button.

### PR DESCRIPTION
**Pull request by devinbinnie**
#### Summary
When we made the fix to disallow the `file:` protocol, we started using `createThumbnailFromPath` to process images. Unfortunately, this function is simply not defined on Linux, causing a crash.

This PR falls back to using the `createFromPath` function for Linux only, which creates a full version of the image. I've capped the image size to use at 1MB so that we don't inflate the memory usage of the downloads dropdown too much.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-60232
Closes #3129

```release-note
Fix a crash in Linux when trying to create a thumbnail from an image
```

### CODE REVIEW

**Review by larkox — APPROVED** [review]

File: src/main/downloadsManager.ts [hunk 1]
```diff
@@ -635,7 +635,15 @@ export class DownloadsManager extends JsonFileManager<DownloadedItems> {
 
         let thumbnailData;
         if (state === 'completed' && item.getMimeType().toLowerCase().startsWith('image/')) {
-            thumbnailData = (await nativeImage.createThumbnailFromPath(overridePath ?? item.getSavePath(), {height: 32, width: 32})).toDataURL();
+            // Linux doesn't support the thumbnail creation so we have to use the base function
+            if (process.platform === 'linux') {
+                // We also will cap this at 1MB so as to not inflate the memory usage of the downloads dropdown
+                if (item.getReceivedBytes() < 1000000) {
```
Comment (M-ZubairAhmed) [inline src/main/downloadsManager.ts:641]: please clarify
> to not inflate the memory usage of the downloads 

Does it mean if image size is greater than 1mb we wont show the preview in the download dropdown

**Review by M-ZubairAhmed — APPROVED** [review]

File: src/main/downloadsManager.ts (hunk 1 above)
Comment (devinbinnie) [reply src/main/downloadsManager.ts:641]: Correct. This is a bit of pre-emptive safety, but I did notice that if you do have a really large image stored in the JSON (like I had before) it will slow down the app significantly, so I want to avoid that.

Comment (M-ZubairAhmed) [reply src/main/downloadsManager.ts:641]: Since this is for images only dont we have access to preview url of the image?

Comment (devinbinnie) [reply src/main/downloadsManager.ts:641]: Not anymore, we can't use the `file:///` protocol which would facilitate that. And we don't want to open up `mattermost-desktop:` to arbitrary files, or else security becomes a concern.

I'd be up for trying to figure out a better solution in the future, but this works for now.

**Comment by licaon-kter** [comment]
what's the timeline for this? Can't save images at all

**Comment by M-ZubairAhmed** [comment]
@licaon-kter its included in v5.9

**Comment by licaon-kter** [comment]
@M-ZubairAhmed _"merged 2 weeks ago"_, 5.9 was released _"6 weeks ago",_ not sure I follow :smile: 

time travel aside, I'm seeing this on 5.9 hence my question

**Comment by devinbinnie** [comment]
@licaon-kter It will go out in the next dot release of v5.9, as well as v5.10 which is scheduled for November 16th.
